apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-pdfgen
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  istio:
    enabled: false
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  accessPolicy:
    inbound:
      rules:
        - application: pale-2-sak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: isbehandlerdialog
          namespace: teamsykefravr
          cluster: dev-gcp
